// styles.js

import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get('window');
const scale = Math.min(width, height) / 375; // Base scale on iPhone 8 dimensions

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 12 * scale,
  },
  label: {
    fontSize: 14 * scale,
    fontWeight: "600",
    color: "#334155",
    marginBottom: 2 * scale,
  },
  condensedLabel: {
    marginBottom: 1 * scale,
    fontSize: 13 * scale,
    fontWeight: "600",
    color: "#334155",
  },
  input: {
    height: 42 * scale,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 14 * scale,
    paddingVertical: 8 * scale,
    borderRadius: 8 * scale,
    backgroundColor: '#F8FAFC',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    color: '#334155',
    fontSize: 15 * scale,
  },
  condensedInput: {
    height: 36 * scale,
    marginBottom: 8 * scale,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 14 * scale,
    paddingVertical: 6 * scale,
    borderRadius: 8 * scale,
    backgroundColor: '#FFFFFF',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    color: '#334155',
    fontSize: 14 * scale,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5 * scale,
    paddingTop: 5 * scale,
  },
  submitButton: {
    backgroundColor: "#3B82F6",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5 * scale,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  visualizeButton: {
    backgroundColor: "#10B981",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5 * scale,
    width: "48%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  savePackageButton: {
    backgroundColor: "#8B5CF6",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5 * scale,
    width: "48%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16 * scale,
    fontWeight: "600",
    textAlign: 'center',
    width: '100%',
    letterSpacing: 0.3,
  },
  itemButton: {
    backgroundColor: "#3B82F6",
    paddingVertical: 10 * scale,
    paddingHorizontal: 15 * scale,
    borderRadius: 8 * scale,
    margin: 5 * scale,
    minWidth: 100 * scale,
    maxWidth: 150 * scale,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  itemsContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    borderRadius: 12 * scale,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    paddingVertical: 8 * scale,
  },
  formContainer: {
    paddingBottom: 10 * scale,
    backgroundColor: '#fff',
    padding: 10 * scale,
    borderRadius: 10 * scale,
    marginVertical: 8 * scale,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  contentContainer: {
    height: 150 * scale,
    marginBottom: 10 * scale,
  },
  bottomButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10 * scale,
    backgroundColor: '#fff',
    paddingHorizontal: 5 * scale,
    marginTop: 10 * scale,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 20 * scale,
    padding: 20 * scale,
    width: "90%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18 * scale,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 15 * scale,
    textAlign: "center",
    width: "100%",
    letterSpacing: 0.3,
  },
  buttonApply: {
    backgroundColor: "#10B981",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    marginVertical: 5 * scale,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonApply1: {
    backgroundColor: "#10B981",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 10 * scale,
    marginVertical: 10 * scale,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonClose: {
    backgroundColor: "#F59E0B",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5 * scale,
    width: "38%",
    flex: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonClose1: {
    backgroundColor: "#EF4444",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    marginVertical: 5 * scale,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonDelete: {
    backgroundColor: "#EF4444",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    alignItems: "center",
    marginHorizontal: 5 * scale,
    width: "30%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonEdit: {
    backgroundColor: "#3B82F6",
    paddingVertical: 10 * scale,
    paddingHorizontal: 20 * scale,
    borderRadius: 8 * scale,
    alignItems: "center",
    marginHorizontal: 5 * scale,
    width: "30%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 12 * scale,
  },
  itemsList: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    paddingHorizontal: 8 * scale,
  },
  itemContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 8 * scale,
    padding: 16 * scale,
    marginVertical: 8 * scale,
    marginHorizontal: 16 * scale,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  itemText: {
    fontSize: 16 * scale,
    fontWeight: "600",
    color: "#2d3436",
    marginBottom: 6 * scale,
    textAlign: "left",
    paddingHorizontal: 6 * scale,
    letterSpacing: 0.2,
  },
  itemDimensions: {
    fontSize: 14 * scale,
    color: "#636e72",
    marginBottom: 4 * scale,
    textAlign: "left",
    paddingHorizontal: 6 * scale,
    letterSpacing: 0.1,
  },
  dimensionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 12 * scale,
    paddingHorizontal: 4 * scale,
  },
  fieldContainer: {
    marginBottom: 12 * scale,
    width: '100%',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
});

export default styles;